<a href="https://colab.research.google.com/github/mukul2508/UCS420_MUKUL-_BANSAL_1024170294/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

temp = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [4]:
temp_corr= temp+ 2
print(temp_corr)

[27 30 33 37 40 29 35 42]


In [7]:
f=(9/5)*temp_corr+32
f

array([ 80.6,  86. ,  91.4,  98.6, 104. ,  84.2,  95. , 107.6])

In [8]:
above_32 = temp_corr[temp_corr > 32]
print(above_32)

[33 37 40 35 42]


In [9]:
count = np.sum(temp_corr > 32)
print(count)

5


In [10]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [13]:
total=np.sum(steps)
total
mean = np.mean(steps)
print(mean)

7016.666666666667


In [14]:
maxi= np.max(steps)
mini= np.min(steps)

print(maxi)
print(mini)

9500
4500


In [15]:
print(np.sum(steps, axis=0))

print(np.sum(steps, axis=1))

[26500 27300 30400]
[18300 24500 14400 27000]


In [16]:
np.unravel_index(np.argmax(steps), steps.shape)

(np.int64(3), np.int64(2))

In [18]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

subset = original[1:5]
print("Subset:", subset)

subset[0] = 999


print( original)
print(subset)

copied = original[1:5].copy()
copied[0] = 500

print("Original:", original)
print("Copied:", copied)

matrix = np.arange(1, 13).reshape(3, 4)

print(matrix)

first_row = matrix[0, :]
last_row = matrix[-1, :]
second_column = matrix[:, 1]
selected = matrix[1:3, 2:4]

print(first_row)
print(last_row)
print(second_column)
print(selected)

flat = matrix.flatten()
rav = matrix.ravel()

print( flat)
print(rav)

rav[0] = 1000

print(rav)
print(matrix)

flat[1] = 2000

print(flat)

print(matrix)

print( matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1000    2    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[   1 2000    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
(3, 4)
2
12
int64


In [19]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("\nX.T:")
print(XT)

XTX = X.T @ X
print("\nX.T @ X:")
print(XTX)

inverse = np.linalg.inv(XTX)
print("\nInverse of X.T @ X:")
print(inverse)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("\nCoefficients:")
print(beta)

print("\nInterpretation:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("\nPredicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Coefficients:
[-0.15921454  0.14083853 10.06302242]

Interpretation:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

Predicted assistance score: 75.27862544779117
