<a href="https://colab.research.google.com/github/mukul2508/UCS420_MUKUL-_BANSAL_1024170294/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

temp = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [4]:
temp_corr= temp+ 2
print(temp_corr)

[27 30 33 37 40 29 35 42]


In [7]:
f=(9/5)*temp_corr+32
f

array([ 80.6,  86. ,  91.4,  98.6, 104. ,  84.2,  95. , 107.6])

In [8]:
above_32 = temp_corr[temp_corr > 32]
print(above_32)

[33 37 40 35 42]


In [9]:
count = np.sum(temp_corr > 32)
print(count)

5
